### PR TITLE
Fix(#501): ShadToast & ShadSonner doesn't react to text direction change

### LINKED ISSUE #501: ShadToast and ShadSonner doesn't react to text direction changes
### Steps to reproduce

1. Run the example app
2. Ensure initial text direction is LTR.
3. Go to Toast\Sonner page
4. Set text direction to RTL.
5. Press the button to show the toast\sonner.
6. Toast\Sonner **should** be in RTL layout BUT it's not.

### Expected results

With `TextDirection.rtl`

Image

### Actual results

With `TextDirection.rtl`

Image

### shadcn_ui version

0.37.4

### Platform

Windows

### Code sample

//

### Screenshots or Video

_No response_

### Logs

_No response_

### Flutter Doctor output

//

### PR DESCRIPTION
**Pull request by DMouayad**
- fix #501 

## Before

https://github.com/user-attachments/assets/f0b7b4f6-c85d-4640-94fc-b06f9aff9a33

## After

https://github.com/user-attachments/assets/47ecc5dd-8186-4d35-99b4-4159fe1d47e8

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making.
- [ ] I followed the [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.
- [ ] I bumped the package version following the [Semantic Versioning](https://semver.org/) guidelines (For now the major is the second number and the minor the third, because the package is not feature complete). For example, if the package is at version `0.18.0` and you introduced a breaking change or a new feature, bump it to `0.19.0`, if you just added a fix or a chore bump it to `0.18.1`.
- [ ] I updated the `CHANGELOG.md` file with a summary of changes made following the format already used.

## Summary by CodeRabbit

* **Bug Fixes**
  * Ensures consistent theme and inherited data propagation across the app.

* **Performance**
  * Reduces unnecessary UI nesting, improving rendering efficiency and responsiveness.

* **Refactor**
  * Consolidates layered wrappers into a single builder while preserving toast/notification behavior and background theme handling.

### CODE REVIEW

**Comment by DMouayad** [comment]
Hey man review it when u got free time. I didn't test this thoroughly so there maybe hidden bugs.

File: lib/src/app.dart [hunk 1]
```diff
@@ -751,29 +751,31 @@ class ShadAppBuilder extends StatelessWidget {
...
+        // The reason for wrapping the [child] with `ShadToaster` and `ShadSonner`
+        // is to ensures that any `InheritedWidget`s introduced by the [builder]
+        // (such as `Directionality`) are inherited by the toaster and sonner.
+        final effectiveChild = child != null
+            ? ShadToaster(child: ShadSonner(child: child!))
+            : child;
+        return ColoredBox(
+          color:
+              backgroundColor ?? ShadTheme.of(context).colorScheme.background,
+          child: builder?.call(context, effectiveChild) ?? effectiveChild,
```
Comment (nank1ro) [inline lib/src/app.dart:776]: I would place `ShadToaster` and `ShadSonner` here, wrapping this `builder?.call` function.
Otherwise if no child is provided, you don't wrap it with `ShadSonner` and `ShadToaster`

Comment (DMouayad) [reply lib/src/app.dart:776]: I'm not sure I understand u correctly but to clarify you want to warp only the builder? or the child passed to builder?

Comment (nank1ro) [reply lib/src/app.dart:776]: I'm making the change myself in this PR, no worries. I'll ping you as soon as I committed

Comment (nank1ro) [reply lib/src/app.dart:776]: @DMouayad ready, let me know

Comment (nank1ro) [reply lib/src/app.dart:776]: In fact the change I did has no effect if the child is null. How you did it before was already enough.
But the fact that child is null never happened to me in my experience with Flutter.

Comment (DMouayad) [reply lib/src/app.dart:776]: Actually I was just thinking if and when the child can be null.
But it's better to be safe than sorry I guess.
It's up to u man but I don't see the point of constructing ShadSonner and ShadToaster if the child is null.

**Review by nank1ro — APPROVED** [review]
LGTM!
